"""ops tables: market_holidays, system_alerts, llm_usage

Revision ID: 503ddfad6740
Revises: d9d9ecd97daa
Create Date: 2026-09-17 18:06:25.520244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '503ddfad6740'
down_revision: Union[str, None] = 'd9d9ecd97daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('feature', sa.String(length=40), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('est_cost_usd', sa.Float(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'model', 'feature', name='uq_llm_usage')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_date'), ['date'], unique=False)

    op.create_table('market_holidays',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('system_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_alerts_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_system_alerts_open', ['resolved_at', 'severity'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_system_alerts_open')
        batch_op.drop_index(batch_op.f('ix_system_alerts_kind'))

    op.drop_table('system_alerts')
    op.drop_table('market_holidays')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_date'))

    op.drop_table('llm_usage')
    # ### end Alembic commands ###
