"""initial schema

Revision ID: 7e2459300fa8
Revises: 
Create Date: 2026-09-17 14:41:03.224349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7e2459300fa8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_daily_bar')
    )
    with op.batch_alter_table('daily_bars', schema=None) as batch_op:
        batch_op.create_index('ix_daily_bars_date', ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_bars_ticker'), ['ticker'], unique=False)

    op.create_table('factor_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('buy_rank', sa.Integer(), nullable=False),
    sa.Column('topsis', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=12), nullable=False),
    sa.Column('regime', sa.String(length=12), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('z', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('contributions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('eligible', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_factor_score')
    )
    with op.batch_alter_table('factor_scores', schema=None) as batch_op:
        batch_op.create_index('ix_factor_scores_date_rank', ['date', 'buy_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_scores_ticker'), ['ticker'], unique=False)

    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_runs_job'), ['job'], unique=False)

    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('sma20', sa.Float(), nullable=True),
    sa.Column('sma50', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('one_month_return', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('rsi_distance', sa.Float(), nullable=True),
    sa.Column('topsis_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', name='uq_snap_date_ticker')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_snapshots_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_id'), ['id'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starting_capital', sa.Float(), nullable=True),
    sa.Column('total_invested', sa.Float(), nullable=True),
    sa.Column('remaining_cash', sa.Float(), nullable=True),
    sa.Column('strategy_summary', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'date', name='uq_model_date')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_model'), ['model'], unique=False)

    op.create_table('rank_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bullets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('watch_out', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('audit_dropped', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_rank_explanation')
    )
    with op.batch_alter_table('rank_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rank_explanations_ticker'), ['ticker'], unique=False)

    op.create_table('universe_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name', 'ticker', 'as_of', name='uq_universe_member')
    )
    with op.batch_alter_table('universe_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universe_members_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_universe_members_index_name'), ['index_name'], unique=False)

    op.create_table('daily_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_portfolio_valdate')
    )
    with op.batch_alter_table('daily_valuations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_valuations_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_valuations_id'), ['id'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('invested_amount', sa.Float(), nullable=True),
    sa.Column('allocation_percent', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('daily_valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_valuations_id'))
        batch_op.drop_index(batch_op.f('ix_daily_valuations_date'))

    op.drop_table('daily_valuations')
    with op.batch_alter_table('universe_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universe_members_index_name'))
        batch_op.drop_index(batch_op.f('ix_universe_members_as_of'))

    op.drop_table('universe_members')
    with op.batch_alter_table('rank_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rank_explanations_ticker'))

    op.drop_table('rank_explanations')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_model'))
        batch_op.drop_index(batch_op.f('ix_portfolios_id'))
        batch_op.drop_index(batch_op.f('ix_portfolios_date'))

    op.drop_table('portfolios')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_date'))

    op.drop_table('market_snapshots')
    with op.batch_alter_table('ingest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_runs_job'))

    op.drop_table('ingest_runs')
    with op.batch_alter_table('factor_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factor_scores_ticker'))
        batch_op.drop_index('ix_factor_scores_date_rank')

    op.drop_table('factor_scores')
    with op.batch_alter_table('daily_bars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_bars_ticker'))
        batch_op.drop_index('ix_daily_bars_date')

    op.drop_table('daily_bars')
    # ### end Alembic commands ###
